tests/cassandra: wait for cassandra server to be available before test
Fix following issue:

```
java.lang.RuntimeException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:146)
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:112)
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:105)
        at org.apache.cassandra.stress.StressProfile.maybeCreateSchema(StressProfile.java:224)
        at org.apache.cassandra.stress.StressProfile.newGenerator(StressProfile.java:689)
        at org.apache.cassandra.stress.StressProfile.printSettings(StressProfile.java:126)
        at org.apache.cassandra.stress.settings.StressSettings.lambda$printSettings$1(StressSettings.java:309)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.apache.cassandra.stress.settings.StressSettings.printSettings(StressSettings.java:309)
        at org.apache.cassandra.stress.Stress.run(Stress.java:107)
        at org.apache.cassandra.stress.Stress.main(Stress.java:63)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:270)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:109)
        at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1813)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1726)
        at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:462)
        at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:181)
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:137)
        ... 10 more
```

test RT:

```
{
  "cassandra.Op.rate": [
    690
  ],
  "cassandra.Op.insert.rate": [
    521
  ],
  "cassandra.Op.simple1.rate": [
    170
  ]
}
```

Signed-off-by: Zou Yu <yux.zou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>