lib/stats.rb: fix samples_remove_early_fails: undefined method '<' for nil:NilClass
/zday/lkp/lib/stats.rb:528:in `block in samples_remove_early_fails': undefined method `<' for nil:NilClass (NoMethodError)
        from /zday/lkp/lib/stats.rb:525:in `each'
        from /zday/lkp/lib/stats.rb:525:in `each_with_index'
        from /zday/lkp/lib/stats.rb:525:in `samples_remove_early_fails'
        from /zday/lkp/lib/bisect.rb:168:in `valid_samples_for_bisect'
	from /zday/lkp/sbin/stats-good-or-bad:49:in `<main>'

Fixes: e29a467f7454 (lib/stats.rb: introduce samples_remove_early_fails to skip early failed rts)
Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>