jobs/phoronix-test-suite.yaml: comment out build-clash-1.0.2 because of known issue
build-clash-1.0.2 packs nix-2.5.1 now. When install build-clashwhich,
we met following known issue:
-----------------------
error: anonymous function at /var/lib/phoronix-test-suite/installed-tests/pts/build-clash-1.0.2/benchmark-compilation/default.nix:24:1 called with unexpected argument 'inNixShell'

       at /var/lib/phoronix-test-suite/installed-tests/pts/build-clash-1.0.2/benchmark-compilation/shell.nix:2:2:

            1| {...}@args:
            2| (import ./. args).shell
             |  ^
-----------------------

Link: https://github.com/haskell-nix/hnix/issues/989
Signed-off-by: Ma Xinjian <xinjianx.ma@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>