lib/git_ext/base.rb: fix "undefined local variable or method `e'"
lib/git_ext/base.rb:87:in `linux_last_release_tag_strategy': undefined local variable or method `e' for #<Git::Base:0x000056397d71b878> (NameError)

Fixes: 8674302d0a29 ("lib: refactor to replace warn with log_warn")
Signed-off-by: Philip Li <philip.li@intel.com>