repo/linux/kvm: change git_am_branch temporarily
kvm/queue triggered an error after being merged:

   arch/x86/kvm/x86.h:361:13: error: 'vcpu' undeclared; did you mean 'cpu'?

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>