lkp install: fix bundler install in centos:7
[root@1ae3ecadce18 /]# gem install bundler
Fetching: bundler-2.3.25.gem (100%)
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.3.0.

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>