lmbench: fix missing depends
gcc -O -DRUSAGE -DHAVE_uint=1 -DHAVE_int64_t=1 -DHAVE_DRAND48 -DHAVE_SCHED_SETAFFINITY=1 -D_FORTIFY_SOURCE=2  -I/usr/include/tirpc -c lib_tcp.c -o ../bin/x86_64-pc-linux-gnu/lib_tcp.o
In file included from lib_tcp.c:9:0:
bench.h:38:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>