filters/need_kernel_version.rb: fix `check_kernel_version': undefined method `split'
/lkp/lkp/src/filters/need_kernel_version.rb:17:in `check_kernel_version': undefined method `split' for nil:NilClass (NoMethodError)

Fixes: 5dc2149d9ca8 ("filters/need_kernel_version.rb: support different version for gcc and clang")
Signed-off-by: Philip Li <philip.li@intel.com>