repo/linux/drm-misc: add git_am_branch
Re: [PATCH v2 1/1] drm/panfrost: Add support for devcoredump
-----------
>    drivers/gpu/drm/panfrost/panfrost_dump.c: In function 'panfrost_core_dump':
> >> drivers/gpu/drm/panfrost/panfrost_dump.c:115:20: error: 'struct panfrost_job' has no member named 'file_priv'
>      115 |         as_nr = job->file_priv->mmu->as;
>          |                    ^~

FWIW -- this is due to recent changes in panfrost, you should rebase on
the latest drm-misc-next which is where the patch will be applied
anyway.
-----------

Link: https://lore.kernel.org/all/YrHWhmNVJnIJ1iaT@maud/
Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>