pkg/mutilate/PKGBUILD: add patch to update SConstruct to python3 version
Fix following issue:

```
  File "/tmp/lkp/mutilate/src/mutilate/SConstruct", line 19

    print "A compiler with C++11 support is required."

          ^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("A compiler with C++11 support is required.")?
```

makepkg RT:

```
{
  "makepkg.pass": [
    1
  ]
}
```

Signed-off-by: Zou Yu <yux.zou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>