tests/kbuild: fix allyesconfig: make autoksyms_recursive failed
Error:
make -j 176 autoksyms_recursive failed
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x20): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status

Reason:
when using gcc-11 instead of gcc-9, there is this error.

Add extern before yylloc in dtc-parser.tab.c also can fix it.
dtc-parser.tab.c only exist after make.
But make twice is not a good approach, and 2nd make will reuse the output of 1st make,
which makes performance test not accurate.

So, make use gcc-9.

Signed-off-by: Jie2x Zhou <jie2x.zhou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>