dump-stat: fix missing positive? in ruby 2.0
/c/lkp-tests/sbin/dump-stat:55:in `<main>': undefined method `positive?' for 0:Fixnum (NoMethodError)

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>