repo/linux/peterz-queue: don't merge branch perf/core temporarily
Commit 7aac804e24af has conflict with commit 3fbefdd0a42d in drm-tip/drm-tip.
-------------
kernel/events/core.c:11507:14: error: implicit declaration of function 'find_pmu_context'; did you mean 'free_pmu_context'? [-Werror=implicit-function-declaration]
-------------

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>