modify stats file of lmbench
when /bw_mem/
     puts "Mem.Bandwidth.MB/sec: #{read_mb_sec}"
   end

这段代码有问题，导致解析出的数据缺少很多键值,所以修改一下
本来想匹配的是这段输出

2022-08-31 10:28:22 ./bin/x86_64-linux-gnu/bw_mem -P 1 268435456 rd
268.44 13805.57

实际匹配了这一段编译输出
/srv/result/lmbench3/2022-10-26/2288hv5-2s40p-256g--b1004/bclinux-R8-U2-iso-x86_64/1-ext4-all-1-4096/crystal.6386389% gr bw_mem lmbench3
gcc -O -DRUSAGE -DHAVE_uint=1 -DHAVE_int64_t=1 -DHAVE_DRAND48 -DHAVE_SCHED_SETAFFINITY=1   -I/usr/include/tirpc -o ../bin/x86_64-pc-linux-gnu/bw_mem bw_mem.c
../bin/x86_64-pc-linux-gnu/lmbench.a -lm -ltirpc
bw_mem.c: In function ‘main’:
bw_mem.c:76:23: warning: implicit declaration of function ‘lmbench_usage’ [-Wimplicit-function-declaration]

正确解析例子
/srv/result/lmbench3/2022-10-26/2288hv5-2s40p-256g--b1004/bclinux-R8-U2-iso-x86_64/1-ext4-all-1-4096/crystal.6386389/lmbench3.json

不正确的例子
/srv/result/lmbench/2022-12-03/taishan200-2280-2s48p-256g--a1010/openeuler-22.03-LTS-SP1-RC1-iso-aarch64/1-ext4-all-1-4096/crystal.6509593/lmbench.json
g -h lmbench /srv/result/lmbench3/2022-10-26/2288hv5-2s40p-256g--b1004/bclinux-R8-U2-iso-x86_64/1-ext4-all-1-4096/crystal.6386389/lmbench3.json
/srv/result/lmbench/2022-12-03/taishan200-2280-2s48p-256g--a1010/openeuler-22.03-LTS-SP1-RC1-iso-aarch64/1-ext4-all-1-4096/crystal.6509593/lmbench.json| tr -d '3' |sc
       2   "lmbench.UDP.usinglocalhost.latency.us": [
       2   "lmbench.TCP.socket.bandwidth.64B.MB/sec": [
       2   "lmbench.TCP.socket.bandwidth.10MB.MB/sec": [
       2   "lmbench.TCP.localhost.latency": [
       2   "lmbench.Rand_mem": [
       2   "lmbench.PIPE.bandwidth.MB/sec": [
       2   "lmbench.MMAP.read_open2close.bandwidth.MB/sec": [
       2   "lmbench.MMAP.read.bandwidth.MB/sec": [
       2   "lmbench.Mmap_Latency": [
       2   "lmbench.Main_mem": [
       2   "lmbench.L2_$": [
       2   "lmbench.L1_$": [
       2   "lmbench.FILE.read.bandwidth.MB/sec": [
       2   "lmbench.CTX.96P.64K.latency.us": [
       2   "lmbench.CTX.96P.16K.latency.us": [
       2   "lmbench.CTX.96P.0K.latency.us": [
       2   "lmbench.CTX.8P.64K.latency.us": [
       2   "lmbench.CTX.8P.16K.latency.us": [
       2   "lmbench.CTX.2P.64K.latency.us": [
       2   "lmbench.CTX.2P.16K.latency.us": [
       2   "lmbench.CTX.2P.0K.latency.us": [
       2   "lmbench.CTX.16P.64K.latency.us": [
       2   "lmbench.CTX.16P.16K.latency.us": [
       2   "lmbench.CONNECT.localhost.latency.us": [
       2   "lmbench.BCOPY.unrolled.bandwidth.MB/sec": [
       2   "lmbench.BCOPY.memory_write.bandwidth.MB/sec": [
       2   "lmbench.BCOPY.memory_read.bandwidth.MB/sec": [
       2   "lmbench.BCOPY.libc.bandwidth.MB/sec": [
       2   "lmbench.AF_UNIX.sock.stream.bandwidth.MB/sec": [
       1   "lmbench.syscall.write.latency.us": [
       1   "lmbench.syscall.syscall.latency.us": [
       1   "lmbench.syscall.stat.latency.us": [
       1   "lmbench.syscall.read.latency.us": [
       1   "lmbench.syscall.open/close.latency.us": [
       1   "lmbench.syscall.fstat.latency.us": [
       1   "lmbench.sig_inst": [
       1   "lmbench.sig_hndl": [
       1   "lmbench.Select.100tcp.latency.us": [
       1   "lmbench.Select.100fd.latency.us": [
       1   "lmbench.Prot_Fault": [
       1   "lmbench.Process.fork+exit.latency.us": [
       1   "lmbench.Process.fork+execve.latency.us": [
       1   "lmbench.Process.fork+/bin/sh.latency.us": [
       1   "lmbench.PIPE.latency.us": [
       1   "lmbench.OPS.integer.mul.latency.ns": [
       1   "lmbench.OPS.integer.div.latency.ns": [
       1   "lmbench.OPS.integer.bit.latency.ns": [
       1   "lmbench.OPS.int64.div.latency.ns": [
       1   "lmbench.OPS.int64.bit.latency.ns": [
       1   "lmbench.OPS.float.mul.latency.ns": [
       1   "lmbench.OPS.float.div.latency.ns": [
       1   "lmbench.OPS.float.add.latency.ns": [
       1   "lmbench.OPS.double.mul.latency.ns": [
       1   "lmbench.OPS.double.div.latency.ns": [
       1   "lmbench.OPS.double.add.latency.ns": [
       1   "lmbench.null_io": [
       1   "lmbench.AF_UNIX.sock.stream.latency.us": [

我确认了下lmbench源代码，"bw_mem -P" 这样匹配是可以的：

wfg /tmp/lmbench% gg 'bw_mem .*-'|cat
doc/bw_mem.8:4:bw_mem \- time memory bandwidth
scripts/lmbench:387:    for i in $HALF; do bw_mem -P $SYNC_MAX $i bcopy; done; echo "" 1>&2
scripts/lmbench:390:    for i in $HALF; do bw_mem -P $SYNC_MAX $i bcopy conflict; done; echo "" 1>&2
scripts/lmbench:393:    for i in $ALL; do bw_mem -P $SYNC_MAX $i bzero; done; echo "" 1>&2
scripts/lmbench:396:    for i in $HALF; do bw_mem -P $SYNC_MAX $i fcp; done; echo "" 1>&2
scripts/lmbench:399:    for i in $HALF; do bw_mem -P $SYNC_MAX $i cp; done; echo "" 1>&2
scripts/lmbench:402:    for i in $ALL; do bw_mem -P $SYNC_MAX $i frd; done; echo "" 1>&2
scripts/lmbench:405:    for i in $ALL; do bw_mem -P $SYNC_MAX $i rd; done; echo "" 1>&2
scripts/lmbench:408:    for i in $ALL; do bw_mem -P $SYNC_MAX $i fwr; done; echo "" 1>&2
scripts/lmbench:411:    for i in $ALL; do bw_mem -P $SYNC_MAX $i wr; done; echo "" 1>&2
scripts/lmbench:414:    for i in $ALL; do bw_mem -P $SYNC_MAX $i rdwr; done; echo "" 1>&2
src/bw_mem.c:4: * Usage: bw_mem [-P <parallelism>] [-W <warmup>] [-N <repetitions>] size what

Signed-off-by: Liu Shuai <lschinasoft@126.com>